export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const FETCH_STAFF = "FETCH_STAFF";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_START = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
// export const LOGOUT_START = "LOGOUT_START";
// export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// export const LOGOUT_FAILED = "LOGOUT_FAILED";
